#!/bin/bash
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=64000
#SBATCH --time=24:00:00
#SBATCH --gres=gpu:t4:1

#SBATCH --job-name=submitter.sh
#SBATCH --account=def-uludagk
#SBATCH --output=/home/u2hussai/nsdmodels/jobs/submitter.sh.%A.out
echo CMD: ./submitter.sh 1 False 100 clip_text.yaml
echo START_TIME: `date`
cd /home/u2hussai/nsdmodels
./submitter.sh 1 False 100 clip_text.yaml
RETURNVAL=$?
echo RETURNVAL=$RETURNVAL
echo END_TIME: `date`
exit $RETURNVAL
